version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.18 #
    steps:
      - checkout # check out source code to working directory
      - run: go build github.com/simonmittag/l0la
      - run: go install github.com/simonmittag/l0la/cmd/l0la
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "Create a temp directory for tests"
          command: |
            mkdir -p /tmp/test-results

      - store_artifacts:
          path: /tmp/artifacts

      - run:
          name: Test Summary for CircleCI
          command: |
            gotestsum --junitfile /tmp/test-results/unit-tests.xml ./...

      - store_test_results:
          path: /tmp/test-results